// Course data built from Armaan's OWL Brightspace (Fall 2026). Dates = when the topic is taught.
window.COURSES = [
 {id:'env', code:'ENVIRSCI 1021F', name:'Environmental Science', emoji:'🌿', color:'mint',
  exams:[{name:'Midterm (Ch 1–4)', date:'2026-10-28'}],
  topics:[
   {id:'e1', name:'The Anthropocene & our footprint', date:'2026-09-09'},
   {id:'e2', name:'Science, uncertainty & policy', date:'2026-09-16'},
   {id:'e3', name:'Ecology: thinking in wholes', date:'2026-09-23'},
   {id:'e4', name:'Evolution & biodiversity', date:'2026-10-07'},
   {id:'e5', name:'Population & environmental health', date:'2026-10-21', locked:true}
  ]},
 {id:'anth', code:'ANTHRO 1025F', name:'Sociocultural Anthropology', emoji:'🌍', color:'lav',
  exams:[{name:'Mid-term (Socio-Cultural)', date:'2026-10-26'}],
  topics:[
   {id:'a1', name:'What is anthropology?', date:'2026-09-09'},
   {id:'a2', name:'Culture & ethnography', date:'2026-09-14'},
   {id:'a3', name:'Culture & selves', date:'2026-09-21'},
   {id:'a4', name:'Culture & the world', date:'2026-09-28'},
   {id:'a5', name:'Culture, power & exchange', date:'2026-10-05'}
  ]},
 {id:'soc', code:'SOCIOLOG 1025A', name:'Society and You', emoji:'👥', color:'peach',
  exams:[{name:'Midterm (Ch 1–7, ~75 MC)', date:'2026-10-27'}],
  topics:[
   {id:'s1', name:'What is sociology?', date:'2026-09-15'},
   {id:'s2', name:'Research methods & Tearoom Trade', date:'2026-09-22'},
   {id:'s3', name:'Culture & norms', date:'2026-09-29'},
   {id:'s4', name:'Socialization & social roles', date:'2026-10-06'},
   {id:'s5', name:'Deviance, crime & social control', date:'2026-10-20'}
  ]},
 {id:'mos', code:'MOS 1021A', name:'Consumer Behaviour & HR', emoji:'💼', color:'sky',
  exams:[{name:'Exam 01 (Sessions 1–3)', date:'2026-10-08'}],
  topics:[
   {id:'m1', name:'Intro to HRM', date:'2026-09-17'},
   {id:'m2', name:'Job analysis & design', date:'2026-09-24'},
   {id:'m3', name:'Talent acquisition', date:'2026-10-01'},
   {id:'m4', name:'Training & performance mgmt', date:'2026-10-22'}
  ]},
 {id:'math', code:'MATH 1228A', name:'Finite Mathematics', emoji:'🎲', color:'lemon',
  exams:[{name:'Term Test 1', date:'2026-10-23'},{name:'Term Test 2', date:'2026-11-13'}],
  topics:[
   {id:'h1', name:'Sets & Venn counting (1.1–1.2)', date:'2026-09-09'},
   {id:'h2', name:'Counting principles (1.3)', date:'2026-09-14'},
   {id:'h3', name:'Permutations (1.4)', date:'2026-09-21'},
   {id:'h4', name:'Combinations (1.5)', date:'2026-09-21'},
   {id:'h5', name:'Multiple groups (1.6)', date:'2026-09-28'},
   {id:'h6', name:'Probability basics (2.1–2.2)', date:'2026-10-02'},
   {id:'h7', name:'Conditional & independence (2.3)', date:'2026-10-07'},
   {id:'h8', name:'Probability trees & Bayes (2.4–2.5)', date:'2026-10-19'},
   {id:'h9', name:'Repeated trials (2.6)', date:'2026-10-26'}
  ]}
];

// q: question, o: options, a: correct index, e: why
window.QUESTIONS = [
// ---------- ENVIRSCI ----------
{t:'e1',q:'What does "Anthropocene" describe?',o:['An official geological epoch after the Holocene','A widely used term for the period when humans became a major influence on Earth systems','A period of natural climate cooling','The era before agriculture'],a:1,e:'It is NOT a formally recognized epoch (geologists rejected it in 2024), but it is widely used to describe profound human influence.'},
{t:'e1',q:'Graphs of the "Great Acceleration" mostly show…',o:['Gradual linear increase from 1800','Rapid acceleration starting around the mid-20th century','A peak in 1970 then decline','No consistent pattern'],a:1,e:'Many unrelated indicators (population, CO₂, water use) bend sharply upward around 1950.'},
{t:'e1',q:'An ecological footprint is…',o:['The population an area can support forever','Land needed to provide resources for, and absorb the waste of, a person or population','Total CO₂ a country emits','The area of protected land'],a:1,e:'Footprint = land to supply resources + assimilate waste.'},
{t:'e1',q:'Carrying capacity is…',o:['Fixed for every environment','The population size an area can support indefinitely','The number of species in an area','A country\'s total consumption'],a:1,e:'And it is NOT fixed — it depends on consumption, technology, trade and ecosystem productivity.'},
{t:'e1',q:'Which is NOT one of Jared Diamond\'s five factors for societal collapse?',o:['Natural climate change','Hostile neighbours','Lack of written language','Loss of friendly neighbours'],a:2,e:'The five: climate change, self-inflicted damage, failure to respond, hostile neighbours, loss of friendly neighbours.'},
{t:'e1',q:'For the Greenland Vikings, "failure to respond to the environment" meant…',o:['They refused to eat fish','They built too many ships','They moved inland','They overused solar power'],a:0,e:'They would not eat fish and refused Inuit help; overgrazing was the self-inflicted damage.'},
{t:'e1',q:'What does the ozone / Montreal Protocol story demonstrate?',o:['Damage repairs itself','Science alone solves problems','Coordinated science, policy, technology and cooperation can reverse dangerous trends','Global agreements don\'t work'],a:2,e:'Detect → identify cause → negotiate → substitute tech → monitor → change trajectory.'},
{t:'e1',q:'Sustainable development means…',o:['Zero economic growth','Meeting present needs without compromising future generations\' ability to meet theirs','Only protecting wilderness','Maximizing GDP'],a:1,e:'Classic definition; the UN 2030 Agenda (2015) built on it.'},
{t:'e1',q:'Sustainability → resilience → regeneration means…',o:['maintain → recover → improve','grow → shrink → stop','recover → maintain → collapse','improve → maintain → recover'],a:0,e:'"Beyond sustainability": sustain = maintain, resilience = recover, regeneration = improve.'},
{t:'e1',q:'The IPAT framework estimates impact from…',o:['Ice, Plants, Animals, Temperature','Population × Affluence × Technology','Policy, Action, Trade','Pollution × Agriculture × Transport'],a:1,e:'I = P × A × T.'},
{t:'e2',q:'Environmental science is best described as…',o:['A social movement to protect nature','An interdisciplinary field drawing on natural sciences, social sciences and humanities','A branch of biology only','Political advocacy'],a:1,e:'Environmentalism advocates; environmental science asks questions. You can be both but they\'re not the same.'},
{t:'e2',q:'Determining which crops suit a soil to help farmers decide is…',o:['Empirical science','Applied science','Not science','Environmentalism'],a:1,e:'Applied = practical use of knowledge. Studying soil composition itself would be empirical.'},
{t:'e2',q:'Which question is NOT scientifically testable?',o:['Why do bats get white-nose syndrome?','Why do humans need to protect bats from WNS?','How have mosquito numbers changed since WNS?','What genetic change made the fungus dangerous?'],a:1,e:'"Need to protect" is an ethical/value question — science can\'t settle it.'},
{t:'e2',q:'Good hypotheses must be…',o:['Proven correct','Testable, replicable and falsifiable','Based on opinion','Long and detailed'],a:1,e:'Hypotheses are supported or rejected — never "proven".'},
{t:'e2',q:'Hypothesis vs prediction:',o:['Same thing','A hypothesis explains; a prediction is the specific outcome you\'d see if the hypothesis is supported','A prediction comes before observation','A hypothesis is a fact'],a:1,e:'Hypothesis = possible explanation. Prediction = expected result in your specific test.'},
{t:'e2',q:'Which study type can show cause and effect?',o:['Observational','Experimental (manipulative) with control groups','Surveys','Case stories'],a:1,e:'Observational studies only show correlation; experiments manipulate variables.'},
{t:'e2',q:'Precision means…',o:['How close a value is to the true value','How close repeated measurements are to each other','Number of samples','How fast you measure'],a:1,e:'Accuracy = close to true value. Precision = close to each other.'},
{t:'e2',q:'Cities with more bicycles have healthier people. This shows…',o:['Bikes cause health','A correlation — other factors may explain it','Nothing at all','Health causes bikes, definitely'],a:1,e:'Correlation ≠ causation.'},
{t:'e2',q:'The precautionary principle says…',o:['Wait for 100% certainty','Act with a safety margin when data are uncertain and consequences could be severe','Never regulate chemicals','Let markets decide'],a:1,e:'E.g., the Montreal Protocol (1987) came before Solomon\'s 1988 confirming studies.'},
{t:'e2',q:'Science CANNOT by itself tell us…',o:['What is happening','Why it might be happening','What risks are acceptable','What interventions might do'],a:2,e:'Acceptable risk, who pays, and priorities are value choices.'},
{t:'e2',q:'Which book sparked the modern environmental movement?',o:['Braiding Sweetgrass','Silent Spring','Collapse','The Population Bomb'],a:1,e:'Rachel Carson, Silent Spring (1962).'},
{t:'e3',q:'Earth is a closed system for ___ but not for ___.',o:['energy, matter','matter, energy','carbon, nitrogen','water, carbon'],a:1,e:'Materially closed (matter cycles), energetically open (sunlight in, heat out).'},
{t:'e3',q:'Which nutrient cycle does NOT involve the atmosphere?',o:['Carbon','Nitrogen','Phosphorus','Water'],a:2,e:'Phosphorus moves through rock, water and organisms.'},
{t:'e3',q:'A keystone species…',o:['Is always the most abundant','Has an impact on its community far larger than its abundance predicts','Is always a plant','Is endangered'],a:1,e:'E.g., sea stars in the Pacific NW intertidal: removing them cut prey species from 15 to 8.'},
{t:'e3',q:'Which is NOT an anthrome?',o:['A botanic garden','Your campus','A cow pasture','A tallgrass prairie'],a:3,e:'A tallgrass prairie is a natural biome; anthromes are human-altered.'},
{t:'e3',q:'Exponential growth happens when…',o:['Resources are limited','There are no limits to growth (birth rate > death rate)','A population is at carrying capacity','Predators increase'],a:1,e:'Often when entering a new environment — but it can\'t last and often ends in collapse.'},
{t:'e3',q:'Snowshoe hares (many offspring, fast reproduction) are…',o:['K-adapted','r-adapted','Keystone species','Producers'],a:1,e:'r-selected: many young, little care. K-selected: few young, more care, near carrying capacity.'},
{t:'e3',q:'Uniform distribution of individuals usually reflects…',o:['Random chance','Negative interactions like territoriality','Social grouping','Patchy habitat'],a:1,e:'Random = independent; clumped = habitat/social; uniform = competition/territory.'},
{t:'e3',q:'Which is bottom-up regulation in Yellowstone?',o:['Wolves prey on elk','A drought kills willows','Bears eat salmon','Elk eat aspen'],a:1,e:'Bottom-up = control from producers/resources. Top-down = predators.'},
{t:'e3',q:'After wolves returned to Yellowstone, which did NOT happen?',o:['Beavers and birds increased','Elk and herbivore populations increased','Streambanks stabilized','Willows prospered'],a:1,e:'Elk DROPPED — a trophic cascade.'},
{t:'e3',q:'Primary succession happens…',o:['On newly exposed surfaces with no biological components','After a fire','In a farm field','Only in oceans'],a:0,e:'Secondary succession happens where biota already modified the environment (e.g., old field).'},
{t:'e3',q:'A limiting factor is…',o:['Any predator','The critical resource whose availability determines population size/distribution','The minimum viable population','A biome type'],a:1,e:'Range of tolerance = the range of that factor within which a species can survive and reproduce.'},
{t:'e3',q:'A population with high species richness but low evenness has…',o:['Few species, equal numbers','Many species but one or two dominate','Many species in equal numbers','One species'],a:1,e:'Richness = how many species; evenness = how equally abundant.'},
{t:'e4',q:'Biodiversity includes variety at which levels?',o:['Species only','Genetic, species and ecosystem','Ecosystem only','Cell and organ'],a:1,e:'Genetic diversity is the population-level one.'},
{t:'e4',q:'Drought leaves mostly large hard seeds. After several generations of finches you\'d predict…',o:['Individual birds grow bigger beaks','Average beak size in the population increases','All small-beaked finches vanish instantly','Finches mutate on demand'],a:1,e:'Individuals are selected; populations evolve.'},
{t:'e4',q:'A bottleneck effect is…',o:['Genetic change after a large part of a population is wiped out','New alleles from mutation','Migration of a few founders','Natural selection for large size'],a:0,e:'Northern elephant seals are the classic example. Founder effect is similar but from dispersal.'},
{t:'e4',q:'Extirpation means…',o:['Extinct everywhere','Gone from one region but still present elsewhere','Endangered','Newly discovered'],a:1,e:'Reintroduction to that region is possible.'},
{t:'e4',q:'The greatest current threat to biodiversity is…',o:['Overharvesting','Pollution','Climate change','Habitat destruction'],a:3,e:'Habitat destruction was a factor in ~70% of bird extinction risk cases.'},
{t:'e4',q:'What wiped out Guam\'s birds?',o:['Disease','Pesticides','An introduced predator (brown tree snake)','Hunting'],a:2,e:'An invasive species case study.'},
{t:'e4',q:'Which vertebrate group is most at risk of extinction?',o:['Birds','Amphibians','Mammals','Reptiles'],a:1,e:'~41% of amphibians vs ~25% mammals, 21% reptiles, 14% birds.'},
{t:'e4',q:'Which is NOT an ecosystem service of biodiversity?',o:['Flood control','Pollination','Recreation','Transportation'],a:3,e:''},
{t:'e4',q:'Canada\'s federal law to prevent extinction/extirpation is…',o:['Endangered Species Act','Species at Risk Act (2002)','CITES','Ramsar'],a:1,e:'ESA is the U.S. law.'},
{t:'e4',q:'The ecosystem approach to conservation…',o:['Focuses on charismatic species like pandas','Protects whole ecosystems and their interactions, often hotspots','Relies on captive breeding','Ignores habitat'],a:1,e:'Single-species = charismatic animals, captive breeding.'},
{t:'e4',q:'Who keeps the Red List of Threatened Species?',o:['UN Environment','IUCN','WWF','Environment Canada'],a:1,e:'Since 1963.'},
{t:'e4',q:'Is ecological change after wolf reintroduction "succession"?',o:['Yes, all change is succession','Yes, vegetation changed','No — succession is community change following disturbance over time','No, animals can\'t affect plants'],a:2,e:'It\'s a trophic cascade, not succession.'},
// ---------- ANTHRO ----------
{t:'a1',q:'Anthropology is distinctive because it is…',o:['Purely biological','Holistic — integrating all parts of human life','Only about the past','Only about language'],a:1,e:'Anthropos = human, -ology = study of.'},
{t:'a1',q:'The four fields of anthropology are…',o:['Biological, archaeology, linguistic, socio-cultural','Psych, soc, history, econ','Medical, legal, forensic, cultural','Physical, chemical, social, spiritual'],a:0,e:''},
{t:'a1',q:'Who is the "father of American anthropology" and popularized the four-field approach?',o:['Malinowski','Franz Boas','Margaret Mead','Sidney Mintz'],a:1,e:'Boas also countered scientific racism with historical particularism.'},
{t:'a1',q:'Who invented ethnographic methods and studied Pacific exchange?',o:['Bronislaw Malinowski','Paul Farmer','Clifford Geertz','Zora Neale Hurston'],a:0,e:'He studied the Kula ring in the Trobriand Islands.'},
{t:'a1',q:'Who wrote Sweetness and Power?',o:['Nancy Scheper-Hughes','Sidney Mintz','Margaret Mead','Paul Farmer'],a:1,e:'A Marxist anthropologist studying food commodities in the Caribbean.'},
{t:'a1',q:'Paul Farmer is known for…',o:['Coming of Age in Samoa','Founding Partners in Health and studying HIV/AIDS in Haiti','Structuralism','The Kula ring'],a:1,e:'AIDS and Accusation: Haiti and the Geography of Blame.'},
{t:'a1',q:'Archaeology studies…',o:['Living languages','The human past through material remains','Primates only','Modern cities'],a:1,e:''},
{t:'a2',q:'E.B. Tylor defined culture as…',o:['Webs of meaning','The complex whole of knowledge, belief, art, law, morals, custom and capabilities acquired as a member of society','A way to satisfy needs','Brain structures'],a:1,e:'The classic 1871 definition.'},
{t:'a2',q:'Historical particularism (Boas) holds that…',o:['Cultures evolve from savage to civilized','Each culture develops through its own history and can\'t be ranked against others','Culture is biological','Culture serves needs'],a:1,e:'It opposed cultural evolutionism, a soft form of scientific racism.'},
{t:'a2',q:'Malinowski\'s functionalism says culture…',o:['Exists to satisfy human needs','Maintains group cohesion','Mirrors brain functions','Is webs of meaning'],a:0,e:'Radcliffe-Brown = structural functionalism (cohesion).'},
{t:'a2',q:'Clifford Geertz is associated with…',o:['Structuralism','Interpretive anthropology — "webs of meaning"','Functionalism','Ethos'],a:1,e:''},
{t:'a2',q:'Claude Lévi-Strauss argued cultural phenomena…',o:['Take the shape of cognitive structures in our brains','Serve needs','Are random','Are biological'],a:0,e:'Structuralism.'},
{t:'a2',q:'Ruth Benedict saw culture as…',o:['Patterns that create an "ethos" expressed in individual psychology','Needs fulfilment','Material objects','Kinship rules'],a:0,e:''},
{t:'a2',q:'Which is NOT a listed characteristic of culture?',o:['Learned','Symbolic','Genetic','Embodied'],a:2,e:'Learned, symbolic, embodied, holistic, integrated, traditional.'},
{t:'a2',q:'Anthropology\'s main research method is…',o:['Lab experiments','Participant observation (ethnography)','National surveys','Fossil dating'],a:1,e:''},
{t:'a2',q:'Judging another culture by your own standards is…',o:['Cultural relativism','Ethnocentrism','Particularism','Functionalism'],a:1,e:'Cultural relativism = understanding a culture on its own terms.'},
{t:'a3',q:'Durkheim\'s mechanical solidarity connects people by…',o:['Interdependent needs','Similarity (e.g., kinship) in small homogeneous groups','Contracts','Money'],a:1,e:'Organic solidarity = connected by needs, like organs, in large heterogeneous groups.'},
{t:'a3',q:'Organic solidarity is typical of…',o:['Small bands','Large heterogeneous societies with stratified labour','Families only','Religious cults'],a:1,e:''},
{t:'a3',q:'Patrilineal descent traces…',o:['The mother\'s line','The father\'s line','Both equally','Neither'],a:1,e:'Matrilineal = mother; ambilineal = both.'},
{t:'a3',q:'Polyandry means…',o:['A man has several wives','A woman has several husbands','One spouse only','Group marriage'],a:1,e:'Polygyny = multiple wives. Both are types of polygamy.'},
{t:'a3',q:'Bride wealth is…',o:['Paid by the bride\'s family to the groom\'s','Paid by the groom to the bride\'s family','Labour given by the groom','A wedding gift from guests'],a:1,e:'Dowry goes the other way; bride service is labour.'},
{t:'a3',q:'Neolocal residence means the couple…',o:['Lives with the father\'s family','Lives with the mother\'s family','Lives in a new separate home','Moves yearly'],a:2,e:''},
{t:'a3',q:'Race, gender, class and nationality are examples of…',o:['Attained identities','Ascribed identities','Performances only','Kinship patterns'],a:1,e:'Ascribed = given by social circumstances; attained = chosen.'},
{t:'a3',q:'Anthropology today views race as…',o:['A biological hierarchy','A social construct with no biological basis','Purely genetic','Irrelevant'],a:1,e:'But it is self-reinforcing through institutions like housing.'},
{t:'a3',q:'Performativity theory says…',o:['There is an innate fixed self','The self is produced through acts of performing it in social context','Identity is genetic','Only actors perform'],a:1,e:''},
{t:'a3',q:'The kinship system most common in Canada (cousins distinct, nuclear family emphasized) is…',o:['Iroquois','Eskimo','Hawaiian','Crow'],a:1,e:'In Iroquois, father\'s brother is also called "father".'},
{t:'a4',q:'Settler colonialism is when…',o:['Territory is controlled only to extract labour and resources','Territory is claimed for colonists to settle and live','Trade happens fairly','A state is born from revolt'],a:1,e:'Economic colonialism = extraction of labour and resources.'},
{t:'a4',q:'Shamans differ from priests because shamans…',o:['Get power from ritual knowledge','Get power directly from the spirit world','Work only in churches','Don\'t deal with illness'],a:1,e:'Priests mediate through ritual knowledge.'},
{t:'a4',q:'Sorcery vs witchcraft:',o:['Sorcery is intentional harm; witchcraft is unintentional','Both are always intentional','Witchcraft is good magic','Same thing'],a:0,e:''},
{t:'a4',q:'Combining different religious beliefs is called…',o:['Cargo cult','Syncretism','Revival','Divination'],a:1,e:'Cargo cults centre on things from the encounter; revival movements call for a return to tradition.'},
{t:'a4',q:'Divination means…',o:['Compelling spirits to act','Using a spiritual connection to gain knowledge','Becoming a god','Healing'],a:1,e:'Magic = compelling the supernatural.'},
{t:'a4',q:'Rituals like weddings and funerals are…',o:['Periodic rituals','Life-stage rituals','Magic','Divination'],a:1,e:'Periodic = seasonal or harvest.'},
{t:'a4',q:'Nationality (as an identity) is…',o:['Ethnic identity tied to state and territory','A biological category','Purely chosen','Kinship'],a:0,e:'It often excludes those who don\'t fit, sometimes leading to removal or genocide.'},
{t:'a4',q:'Social class is…',o:['Only about money','A hierarchical system including wealth AND cultural factors like language and dress','Fixed forever','The same as ethnicity'],a:1,e:'It can change but is very difficult to (Pygmalion / My Fair Lady).'},
{t:'a5',q:'A "band" political organization is…',o:['Large and bureaucratic','Small (~30), nomadic, kinship-based and egalitarian','A hereditary chiefdom','A state'],a:1,e:'Tribes ~100+ with a "big man"; chiefdoms 1000+ with a hereditary chief.'},
{t:'a5',q:'The typology of bands, tribes, chiefdoms and states…',o:['Is an evolutionary ladder','Is NOT an evolution — each has a different kind of complexity','Ranks states as most advanced','Applies only to Africa'],a:1,e:''},
{t:'a5',q:'How do the !Kung Bushmen stop people gaining too much power?',o:['Witch purges','Ridicule and jokes','Elections','Exile'],a:1,e:'The Tiv link accumulated wealth to witchcraft. "Eating Christmas in the Kalahari" shows this.'},
{t:'a5',q:'James Scott\'s Seeing Like a State argues states…',o:['Make subjects "legible" through quantification, which can obscure local conditions','Always help locals','Avoid bureaucracy','Use gift exchange'],a:0,e:''},
{t:'a5',q:'For Mauss, the hau of a gift is…',o:['Its price','Its spirit, which must be returned to keep balance','A tax','A contract'],a:1,e:'Based on Māori exchange; the relationship is as much the object as the item.'},
{t:'a5',q:'In the Kula ring, mwali (armbands) move ___ and soulava (necklaces) move ___.',o:['clockwise, counter-clockwise','counter-clockwise, clockwise','both clockwise','randomly'],a:1,e:'Kula items can only be traded for each other and must keep moving.'},
{t:'a5',q:'A commodity is…',o:['A gift with a spirit','A good with uniform value regardless of source or producer','Always handmade','A Kula item'],a:1,e:'Oil, soy, gold, lumber.'},
{t:'a5',q:'Matsutake mushrooms (Tsing) show that goods…',o:['Always stay commodities','Can move from non-monetary value, to commodity, to gift','Have no social meaning','Are only sold in Oregon'],a:1,e:'Foraged in Oregon → graded in markets → given as gifts in Japan.'},
{t:'a5',q:'Haiti\'s poverty is linked in lecture to…',o:['Its origin in a slave revolt, then ostracism and lack of trade/recognition','Natural disasters only','Its culture','Overpopulation'],a:0,e:'Paul Farmer studied the HIV epidemic there.'},
{t:'a5',q:'Anthropology defines an economy as…',o:['The stock market','How societies create, exchange and distribute value — first of all a social practice','Only money','Government budgets'],a:1,e:'Politics = how we create, exchange and distribute POWER.'},
// ---------- SOCIOLOGY ----------
{t:'s1',q:'C. Wright Mills\' "sociological imagination" is…',o:['Daydreaming about society','Awareness of the link between personal experience and the wider society that shapes it','A research method','A theory of crime'],a:1,e:'1959.'},
{t:'s1',q:'Agency vs structure:',o:['Agency = social patterns; structure = choices','Agency = people\'s capacity to choose; structure = the framework of patterns shaping interaction','Same thing','Both are norms'],a:1,e:''},
{t:'s1',q:'Macrosociology studies…',o:['Small group interactions','Trends among and between large groups/societies','Individuals\' brains','Single families'],a:1,e:''},
{t:'s1',q:'Who coined positivism?',o:['Marx','Auguste Comte','Weber','Durkheim'],a:1,e:'Martineau was the first female sociologist.'},
{t:'s1',q:'Verstehen (interpretive understanding) is associated with…',o:['Durkheim','Max Weber','Comte','Marx'],a:1,e:'Weber also wrote The Protestant Ethic and the Spirit of Capitalism.'},
{t:'s1',q:'Durkheim is known for…',o:['Social facts and anomie','Class struggle','Dramaturgy','The looking-glass self'],a:0,e:''},
{t:'s1',q:'Robert Merton distinguished manifest functions from…',o:['Latent functions','Mores','Agency','Norms'],a:0,e:'Manifest = easily observed/intended; latent = unintended; latent dysfunctions = unintended harm.'},
{t:'s1',q:'Conflict theory (Marx) centres on…',o:['Social harmony','Class struggle between bourgeoisie and proletariat','Symbols','Small groups'],a:1,e:'Bourgeoisie own the means of production.'},
{t:'s1',q:'Symbolic interactionism is…',o:['A macro theory','A micro theory of how people act based on meanings created in interaction','Marxist','Positivist'],a:1,e:'Mead, Blumer, Goffman (dramaturgy).'},
{t:'s2',q:'Deductive reasoning moves from…',o:['Data to theory','Theory to hypothesis to data','Interviews to theory','Opinion to fact'],a:1,e:'Inductive (and grounded theory) moves from data to theory.'},
{t:'s2',q:'Operationalization means…',o:['Running an experiment','Defining an abstract concept in measurable terms','Getting ethics approval','Sampling'],a:1,e:'E.g., "social class" measured by education, income, occupation.'},
{t:'s2',q:'A correlation that is actually caused by a third variable is…',o:['Causal','Spurious','Negative','Positive'],a:1,e:''},
{t:'s2',q:'Qualitative methods typically…',o:['Use predefined variables and statistics','Begin with open-ended questions via interviews, focus groups, content analysis','Require random samples','Are never used'],a:1,e:''},
{t:'s2',q:'Canada\'s ethics standard for research with humans is…',o:['The Belmont Report','The Tri-Council Policy Statement','The Charter','The IRB Act'],a:1,e:'Reviewed by Research Ethics Boards (REBs); requires informed consent.'},
{t:'s2',q:'Laud Humphreys\' Tearoom Trade used which role to observe?',o:['Police officer','"Watchqueen" (lookout)','Interviewer','Survey designer'],a:1,e:''},
{t:'s2',q:'Humphreys\' main ethical problem was…',o:['Too small a sample','Deception: tracing licence plates and interviewing men under false pretenses','Using surveys','Publishing too late'],a:1,e:'He added them to a health survey, changed his appearance, and waited a year.'},
{t:'s2',q:'Secondary analysis uses…',o:['New interviews','Data already collected by others','Experiments','Participant observation'],a:1,e:''},
{t:'s3',q:'Folkways are…',o:['Strictly enforced, codified rules','Informal norms like etiquette, not strictly enforced','So strong that even thinking of breaking them disgusts','Laws'],a:1,e:'Mores = formal and seriously enforced (theft, murder). Taboos = strongest (cannibalism, incest).'},
{t:'s3',q:'Cannibalism or incest violates…',o:['Folkways','Mores','Taboos','Prescriptive norms'],a:2,e:''},
{t:'s3',q:'Bourdieu\'s cultural capital refers to…',o:['Money','Non-financial assets like education, taste and style that give advantage','Cities','Mass media'],a:1,e:'Habitus = deeply ingrained habits and dispositions.'},
{t:'s3',q:'The Sapir-Whorf hypothesis says…',o:['Language structures how we perceive the world','Culture is genetic','All languages are the same','Norms are universal'],a:0,e:'Strong form = linguistic determinism; weak form = linguistic relativity.'},
{t:'s3',q:'Preferring other cultures over your own is…',o:['Ethnocentrism','Xenocentrism','Cultural relativism','Culture shock'],a:1,e:''},
{t:'s3',q:'A counterculture…',o:['Is a small group within the mainstream','Actively rejects and opposes mainstream values','Is high culture','Is popular culture'],a:1,e:'A subculture differs but doesn\'t reject.'},
{t:'s3',q:'Baudrillard is associated with…',o:['Habitus','Simulacra','Strain theory','Anomie'],a:1,e:''},
{t:'s4',q:'Cooley\'s looking-glass self involves…',o:['Imagining how we appear, how others judge it, and incorporating those judgements','Mirrors','Genetics','Formal sanctions'],a:0,e:''},
{t:'s4',q:'Mead\'s "I" vs "Me":',o:['"I" = spontaneous self; "Me" = socialized self from others\' expectations','Same','"Me" is impulsive','"I" is the generalized other'],a:0,e:''},
{t:'s4',q:'A master status is…',o:['The status that dominates others and shapes identity','Your job title only','An achieved status','A role'],a:0,e:'Ascribed = assigned (e.g., age); achieved = earned.'},
{t:'s4',q:'Role conflict vs role strain:',o:['Conflict = between different roles; strain = within one role','Same thing','Strain = between roles','Neither involves roles'],a:0,e:'E.g., student vs employee = conflict; too many demands as a student = strain.'},
{t:'s4',q:'Lareau found middle-class parents use…',o:['Natural growth','Concerted cultivation: organized activities and reasoning','Directives','No strategy'],a:1,e:'Working-class/poor families use the "accomplishment of natural growth". Class mattered more than race.'},
{t:'s4',q:'Middle-class kids in Lareau\'s study developed…',o:['Distrust of adults','An emerging sense of entitlement with institutions','Less vocabulary','More free time'],a:1,e:''},
{t:'s4',q:'Prisons and psychiatric hospitals are examples of…',o:['Primary groups','Total institutions (Goffman)','Bureaucracies','Peer groups'],a:1,e:'They often involve resocialization and degradation ceremonies.'},
{t:'s4',q:'Asch\'s line experiments demonstrated…',o:['Groupthink','Conformity','Social loafing','Facilitation'],a:1,e:'Groupthink = Janis (1972).'},
{t:'s4',q:'Which is NOT a feature of Weber\'s ideal bureaucracy?',o:['Division of labour','Hierarchy of authority','Personal favouritism','Rules and regulations'],a:2,e:'Impersonality is a feature.'},
{t:'s4',q:'Preparing for a future role (e.g., studying business before a job) is…',o:['Primary socialization','Anticipatory socialization','Resocialization','Degradation'],a:1,e:''},
{t:'s5',q:'In Merton\'s strain theory, accepting goals but using illegitimate means is…',o:['Conformity','Innovation','Ritualism','Retreatism'],a:1,e:'Ritualism rejects goals but keeps means; retreatism rejects both; rebellion replaces both.'},
{t:'s5',q:'Rejecting both cultural goals and legitimate means is…',o:['Innovation','Ritualism','Retreatism','Rebellion'],a:2,e:''},
{t:'s5',q:'Sutherland\'s differential association theory says crime is…',o:['Genetic','Learned in interaction with intimate groups, like any behaviour','Caused by poverty alone','Random'],a:1,e:''},
{t:'s5',q:'Hirschi\'s social control theory names four bonds:',o:['Attachment, commitment, involvement, belief','Goals, means, norms, roles','Id, ego, superego, self','Family, school, work, media'],a:0,e:''},
{t:'s5',q:'Sykes and Matza\'s "techniques of neutralization" are…',o:['Police tactics','Justifications that let offenders rationalize deviance','Types of prisons','Forms of punishment'],a:1,e:''},
{t:'s5',q:'In The Saints and the Roughnecks, why were the Saints seen as good kids?',o:['They committed less delinquency','Visibility, demeanor, and class-based perceptual bias','They were never caught doing anything','Their parents were police'],a:1,e:'Both gangs had about equal delinquency; social class shaped reactions and later careers.'},
{t:'s5',q:'Relationship between crime and deviance:',o:['All deviance is crime','All crime is deviant, but not all deviance is crime','They are unrelated','Crime is broader'],a:1,e:''},
{t:'s5',q:'Informal social control applies sanctions mostly for violating…',o:['Mores','Folkways','Laws','Taboos only'],a:1,e:'Formal social control (police, courts) targets mores and laws.'},
// ---------- MOS ----------
{t:'m1',q:'HRM is…',o:['Payroll only','Practices, policies and systems that influence employee attitudes, behaviours and performance toward organizational goals','Hiring only','Legal compliance only'],a:1,e:''},
{t:'m1',q:'Human capital theory (Becker, Mincer, Schultz) views employees as…',o:['Costs to minimize','Valuable assets — education, skills and experience that are rare and hard to copy','Interchangeable parts','Machines'],a:1,e:'Critics: intangibles alone aren\'t enough without management and motivation.'},
{t:'m1',q:'The "classical view" of HRM (Taylor\'s scientific management) saw employees as…',o:['Assets','Interchangeable, expendable costs','Partners','Strategists'],a:1,e:''},
{t:'m1',q:'The Hawthorne Studies (1924–32) studied…',o:['Pay and turnover','The link between work conditions and productivity','Hiring tests','Unions'],a:1,e:'They led to Elton Mayo\'s Human Relations Movement.'},
{t:'m1',q:'Strategic HRM means…',o:['HR only implements strategy','Including HR in both FORMULATING and IMPLEMENTING strategy','Cutting HR costs','Outsourcing HR'],a:1,e:''},
{t:'m1',q:'A protean career (Douglas Hall, 1976) is…',o:['Linear, one employer','Self-directed and values-driven, changing direction over time','Government work','Unionized'],a:1,e:''},
{t:'m1',q:'Employee engagement measures…',o:['Satisfaction with pay','Commitment to and investment in one\'s work','Attendance','Productivity'],a:1,e:'Job satisfaction = fulfilment from appraising job experiences.'},
{t:'m1',q:'Rynes, Colbert & Brown (2002) found HR professionals\' beliefs…',o:['Matched research closely','Often didn\'t match research findings — habit and fads won out','Were all wrong','Were irrelevant'],a:1,e:'This is the case for Evidence-Based HRM.'},
{t:'m1',q:'A research hypothesis is…',o:['The knowledge gap','A statement of what you expect the study to show','The data','The method'],a:1,e:'Order: question → hypothesis → methods → findings.'},
{t:'m2',q:'A job vs a position:',o:['Same thing','A job is a group of TDRs; a position is that job assigned to a specific person in an organization','A position is broader','A job is one task'],a:1,e:'TDRs = tasks, duties, responsibilities.'},
{t:'m2',q:'KSAOs stand for…',o:['Knowledge, Skills, Abilities, Other characteristics','Keys, Systems, Assets, Outputs','Knowledge, Strategy, Action, Outcomes','None'],a:0,e:''},
{t:'m2',q:'Job analysis is called…',o:['Optional paperwork','The building block of everything HR does','Only for executives','Payroll'],a:1,e:'It covers job content, context and requirements.'},
{t:'m2',q:'The class\'s 4-step job analysis process begins with…',o:['Writing the job description','Reviewing relevant background information','Interviewing incumbents','Posting the job'],a:1,e:'Then determine sources → gather and analyze → develop descriptions and specs.'},
{t:'m2',q:'The NOC is…',o:['A US database','Canada\'s standardized reference for occupational categories','A personality test','A union'],a:1,e:'OaSIS = Canada\'s newer database of HR characteristics for occupations.'},
{t:'m2',q:'Which SME gives the most accurate data about performing job tasks?',o:['Job analysts','Supervisors','Incumbents','Customers'],a:2,e:'Supervisors = importance of duties; analysts = context and comparison.'},
{t:'m2',q:'Functional Job Analysis (FJA) rates task statements on…',o:['People, Data, Things','Cognitive, Physical, Social','195 job elements','Abilities only'],a:0,e:'F-JAS (Fleishman) = 73 ability scales in 5 domains; PAQ = 195 elements in 6 categories.'},
{t:'m2',q:'Job analysis produces two key documents:',o:['Resume and cover letter','Job description and job specification','Org chart and budget','Offer and contract'],a:1,e:'Description = the job (TDRs); specification = the person (KSAOs).'},
{t:'m2',q:'The PAQ evaluates…',o:['People/Data/Things','195 job elements across 6 categories','73 abilities','Competencies only'],a:1,e:''},
{t:'m3',q:'Talent acquisition includes…',o:['Recruitment only','Selection only','Both recruitment (attracting) and selection (deciding)','Training'],a:2,e:''},
{t:'m3',q:'A benefit of internal recruitment is…',o:['New ideas','Quicker and cheaper, boosts engagement, both sides "well known"','Avoids homogeneity','Wider pool'],a:1,e:'External recruitment brings new ideas and avoids a homogeneous workforce.'},
{t:'m3',q:'A Realistic Job Preview…',o:['Hides the job\'s downsides','Gives an honest picture of the job, raising trust and commitment and reducing turnover','Is a salary offer','Is an interview'],a:1,e:'E.g., the PetSmart and IKEA RJPs.'},
{t:'m3',q:'The employee value proposition is…',o:['Salary only','The core of an employer brand: the broader benefits of working there','A selection test','A job ad'],a:1,e:''},
{t:'m3',q:'Reliability means a selection tool…',o:['Measures what it should','Gives consistent results, free from random error','Is legal','Looks fair'],a:1,e:'Types: test-retest, interrater, internal.'},
{t:'m3',q:'Validity means a selection tool…',o:['Is consistent','Accurately measures what it\'s intended to measure','Is cheap','Is popular'],a:1,e:''},
{t:'m3',q:'Which validity is judged by SMEs checking that a tool covers job-relevant traits?',o:['Face','Content','Criterion-related','Construct'],a:1,e:'Face validity = the test-taker\'s subjective view.'},
{t:'m3',q:'Criterion-related validity is shown through…',o:['Convergent and discriminant validation','Concurrent and predictive validation','SME review','Applicant opinion'],a:1,e:'Construct validity uses convergent and discriminant validation.'},
{t:'m3',q:'Order of the selection process:',o:['Interview → screening → testing','Screening → testing → interviews → background/references → decision','Testing → decision → interview','References first'],a:1,e:''},
{t:'m3',q:'Referral applicants tend to…',o:['Be lower quality','Be higher quality, have more realistic expectations, and cost less','Quit faster','Be illegal'],a:1,e:''},
{t:'m3',q:'Face validity is…',o:['Statistical','A subjective judgement from the test-taker\'s view of whether the test seems fair and relevant','Set by SMEs','Predictive'],a:1,e:''},
{t:'m4',q:'Performance management mainly aims to…',o:['Fire people','Understand, support and improve employee performance to align with strategy','Set pay only','Recruit'],a:1,e:'Session 04 handouts will be posted Oct 22. More questions will arrive with them.'},
{t:'m4',q:'Evaluating whether training "worked" is…',o:['Optional','A key step of effective training design','Done before training','Only for executives'],a:1,e:''},
{t:'m4',q:'Rater errors like the halo effect hurt an appraisal\'s…',o:['Cost','Validity and reliability','Legality only','Speed'],a:1,e:''}
];
