import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.45.4";
import * as webpush from "jsr:@negrel/webpush@0.3.0";

// Server key: older projects expose SUPABASE_SERVICE_ROLE_KEY, newer ones SUPABASE_SECRET_KEYS (JSON).
function serverKey(): string {
  const legacy = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (legacy) return legacy;
  try { const j = JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") || "{}"); return j.default || Object.values(j)[0] as string || ""; } catch { return ""; }
}

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-loop-cron",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { ...CORS, "Content-Type": "application/json" } });
const admin = createClient(Deno.env.get("SUPABASE_URL")!, serverKey());

const b64u = (b: Uint8Array) => btoa(String.fromCharCode(...b)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const unb64u = (s: string) => Uint8Array.from(atob(s.replace(/-/g, "+").replace(/_/g, "/") + "==".slice(0, (4 - s.length % 4) % 4)), (c) => c.charCodeAt(0));

// Keys are generated by this function on first use and kept in a service-role-only table.
async function getKeys() {
  let { data } = await admin.from("loop_push_keys").select("*").eq("id", 1).maybeSingle();
  if (!data) {
    const k = await webpush.generateVapidKeys({ extractable: true });
    const jwk = await webpush.exportVapidKeys(k);
    const pub = b64u(new Uint8Array([4, ...unb64u(jwk.publicKey.x!), ...unb64u(jwk.publicKey.y!)]));
    const cron = b64u(crypto.getRandomValues(new Uint8Array(24)));
    await admin.from("loop_push_keys").insert({ id: 1, public_key: pub, vapid: jwk, cron_key: cron });
    ({ data } = await admin.from("loop_push_keys").select("*").eq("id", 1).maybeSingle());
  }
  return data!;
}
let APP: any = null;
async function appServer() {
  if (APP) return APP;
  const k = await getKeys();
  APP = await webpush.ApplicationServer.new({ contactInformation: "mailto:loop-notifications@users.noreply.github.com", vapidKeys: await webpush.importVapidKeys(k.vapid) });
  return APP;
}

async function send(sub: any, msg: { title: string; body?: string; tag?: string; url?: string }) {
  const app = await appServer();
  try {
    await app.subscribe({ endpoint: sub.endpoint, keys: { p256dh: sub.p256dh, auth: sub.auth } })
      .pushTextMessage(JSON.stringify(msg), { ttl: 900, urgency: webpush.Urgency.Normal, topic: (msg.tag || "loop").replace(/[^A-Za-z0-9_-]/g, "").slice(0, 32) || "loop" });
    await admin.from("loop_push_subs").update({ last_ok: new Date().toISOString() }).eq("id", sub.id);
    return true;
  } catch (e: any) {
    const st = e?.response?.status;
    if (st === 404 || st === 410) await admin.from("loop_push_subs").delete().eq("id", sub.id);
    return false;
  }
}

/* ---- schedule logic (mirrors the app) ---- */
const WD = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];
const t2m = (t?: string) => { if (!t) return null; const [h, m] = t.split(":").map(Number); return h * 60 + (m || 0); };
const addDays = (d: string, n: number) => { const x = new Date(d + "T12:00:00Z"); x.setUTCDate(x.getUTCDate() + n); return x.toISOString().slice(0, 10); };
const wdOf = (d: string) => WD[new Date(d + "T12:00:00Z").getUTCDay()];
function occursOn(e: any, d: string) {
  if (e.date && !(e.days && e.days.length)) return e.date === d;
  if (e.days && e.days.length) { if (e.startDate && d < e.startDate) return false; if (e.endDate && d > e.endDate) return false; if (e.except && e.except.includes(d)) return false; return e.days.includes(wdOf(d)); }
  return false;
}
function localNow(tz: string) {
  let p: Record<string, string> = {};
  try { new Intl.DateTimeFormat("en-CA", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(new Date()).forEach((x) => p[x.type] = x.value); }
  catch { return localNow("America/Toronto"); }
  return { d: `${p.year}-${p.month}-${p.day}`, m: (Number(p.hour) % 24) * 60 + Number(p.minute) };
}
const fmt12 = (t: string) => { const m = t2m(t)!; const h = Math.floor(m / 60), mm = m % 60; return `${h % 12 || 12}${mm ? ":" + String(mm).padStart(2, "0") : ""}${h < 12 ? "am" : "pm"}`; };
const EMO: Record<string, string> = { class: "📚", club: "🎭", appointment: "🩺", exam: "📝", deadline: "⏰", study: "🧠", work: "💼", other: "✨" };

function dueItems(S: any, prefs: any, d: string, m: number) {
  const out: { k: string; f: number; msg: any }[] = [];
  const events = Array.isArray(S?.events) ? S.events : [];
  if (prefs.classes !== false) {
    for (const e of events) {
      if (!e.start || !occursOn(e, d)) continue;
      const r = e.remind == null ? 15 : Number(e.remind);
      if (r < 0 || r >= 1440) continue;
      const st = t2m(e.start)!;
      out.push({ k: `ev|${d}|${e.id}`, f: st - r, msg: { title: `${EMO[e.kind] || "✨"} ${e.title} ${r <= 0 ? "is starting" : `in ${r} min`}`, body: [fmt12(e.start), e.location].filter(Boolean).join(" · "), tag: `ev-${e.id}` } });
    }
    const tm = addDays(d, 1);
    for (const e of events) {
      if (Number(e.remind) !== 1440 || !occursOn(e, tm)) continue;
      out.push({ k: `evd|${tm}|${e.id}`, f: 18 * 60, msg: { title: `Tomorrow: ${e.title}`, body: [e.start ? fmt12(e.start) : "", e.location].filter(Boolean).join(" · "), tag: `evd-${e.id}` } });
    }
  }
  if (prefs.deadlines !== false) {
    const tm = addDays(d, 1), big: string[] = [];
    for (const c of S?.courses || []) for (const x of c.exams || []) if (x.date === d || x.date === tm) big.push(`${c.code || c.name} · ${x.name}${x.date === d ? " (today)" : " (tomorrow)"}`);
    for (const a of S?.apps || []) if ((a.deadline === d || a.deadline === tm) && a.status === "saved") big.push(`Apply: ${a.org}${a.deadline === d ? " (today)" : " (tomorrow)"}`);
    if (big.length) out.push({ k: `dg|${d}`, f: t2m(prefs.quietEnd || "08:00")! + 5, msg: { title: `📅 ${big.length} exam${big.length > 1 ? "s" : ""}/deadline${big.length > 1 ? "s" : ""} coming up`, body: big.slice(0, 3).join(" · "), tag: "digest" } });
  }
  if (prefs.study !== false) {
    const done = S?.log?.[d]?.n || 0, goal = S?.settings?.len || 8;
    const due = Object.values(S?.q || {}).filter((r: any) => r && r.reps && r.due <= d).length;
    if (done < goal && due > 0) out.push({ k: `st|${d}`, f: t2m(prefs.studyTime || "18:00")!, msg: { title: `🧠 ${due} review${due > 1 ? "s are" : " is"} ready`, body: "About 5 minutes keeps them from fading. Tap to start.", tag: "study", url: "/?go=daily" } });
  }
  return out.filter((x) => x.f <= m && x.f > m - 7);
}
function quiet(prefs: any, m: number) {
  const qs = t2m(prefs.quietStart || "22:00")!, qe = t2m(prefs.quietEnd || "08:00")!;
  if (qs === qe) return false;
  return qs > qe ? (m >= qs || m < qe) : (m >= qs && m < qe);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "method" }, 405);
  let body: any = {};
  try { body = await req.json(); } catch { /* empty */ }
  const action = String(body.action || "");

  if (action === "key") return json({ publicKey: (await getKeys()).public_key });

  if (action === "test") {
    const token = (req.headers.get("Authorization") || "").replace("Bearer ", "");
    const { data: u } = await admin.auth.getUser(token);
    if (!u?.user) return json({ error: "auth", message: "Sign in first." }, 401);
    const { data: subs } = await admin.from("loop_push_subs").select("*").eq("user_id", u.user.id);
    let n = 0;
    for (const s of subs || []) if (await send(s, { title: "🔔 Loop notifications are on", body: "You'll get reminders even when Loop is closed.", tag: "test" })) n++;
    return json({ sent: n, devices: (subs || []).length });
  }

  if (action === "run") {
    const k = await getKeys();
    if (req.headers.get("x-loop-cron") !== k.cron_key) return json({ error: "forbidden" }, 403);
    const { data: subs } = await admin.from("loop_push_subs").select("*");
    const byUser = new Map<string, any[]>();
    for (const s of subs || []) { if (!byUser.has(s.user_id)) byUser.set(s.user_id, []); byUser.get(s.user_id)!.push(s); }
    let sent = 0;
    for (const [uid, list] of byUser) {
      const { data: row } = await admin.from("studybuddy_progress").select("state").eq("user_id", uid).maybeSingle();
      if (!row?.state) continue;
      const S = row.state, tz = list[0].tz || "America/Toronto", prefs = { ...(list[0].prefs || {}), ...(S.settings?.push || {}) };
      if (S.settings?.push?.on === false) continue;
      const { d, m } = localNow(tz);
      if (quiet(prefs, m)) continue;
      for (const it of dueItems(S, prefs, d, m)) {
        const { error } = await admin.from("loop_push_sent").insert({ user_id: uid, k: it.k });
        if (error) continue; // already sent (primary key)
        for (const s of list) if (await send(s, it.msg)) sent++;
      }
    }
    await admin.from("loop_push_sent").delete().lt("sent_at", new Date(Date.now() - 8 * 864e5).toISOString());
    return json({ users: byUser.size, sent });
  }
  return json({ error: "unknown_action" }, 400);
});
